"""ComfyUI_TJS custom node package."""

from .tjs_nodes import (
    NODE_CLASS_MAPPINGS as _SAMPLER_CLASS,
    NODE_DISPLAY_NAME_MAPPINGS as _SAMPLER_DISPLAY,
)

NODE_CLASS_MAPPINGS = {**_SAMPLER_CLASS}
NODE_DISPLAY_NAME_MAPPINGS = {**_SAMPLER_DISPLAY}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
